### ISSUE TITLE
Using multiple inference types

### ISSUE THREAD

**Issue by MajlindaLlugiqi** [liveontologies/elk-reasoner#62] opened 2021-12-16 14:53 UTC
I am trying to save an inferred ontology with:

````OWLReasonerFactory reasonerFactory = new ElkReasonerFactory();
    OWLReasoner reasoner = reasonerFactory.createReasoner(localUni);
    reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY);
    List<InferredAxiomGenerator<? extends OWLAxiom>> gens = Collections.singletonList(
            new InferredSubClassAxiomGenerator());
    OWLOntology infOnt = manager.createOntology();
    InferredOntologyGenerator iog = new InferredOntologyGenerator(reasoner, gens);
    OWLDataFactory f = OWLManager.getOWLDataFactory();
    iog.fillOntology(manager.getOWLDataFactory(), infOnt);

//     Save the inferred ontology.
    manager.saveOntology(infOnt, new FunctionalSyntaxDocumentFormat(), IRI.create((new File("lib/kidney_dataset_ontology-inferred-ELK.owl").toURI())));
````

Is there a way I can use multiple inference types, because when I do this the inferred ontology has less axioms than the original ontology?

**Comment by ykazakov** [comment] 2021-12-17 08:25
`InferredOntologyGenerator` is a part of [owl api](https://github.com/owlcs/owlapi). Perhaps you should ask this question there. Did you check the result produced using other reasoners, e.g., HermiT? Does it contain more axioms?

As far as I remember, `InferredOntologyGenerator` just produces the entailed axioms of some specific shapes (e.g., subsumptions and class equivalences) and does not copy the original axioms from the ontology.

**Comment by MajlindaLlugiqi** [comment] 2021-12-17 09:59
Thank you for your swift reply.

Yes I checked the results using HermiT, and it contains more axioms than the original one. 

I tried ELK in Protege as well (Export inferred axioms as ontology) but I get "OWL API reasoner method is not implemented: getSuperObjectProperties(OWLObjectPropertyExpression, boolean)" and "Protege has just called an OWL API method that ELK currently does not fully support." and it is recommended to switch off some of the inference types.

**Comment by MajlindaLlugiqi** [comment] 2021-12-17 10:55
I am using a part of SNOMED and it is in EL. I know that 'only class hierarchy inferences are generated', but I cannot use more than one inference-type. 

HermiT generates extra axioms while keeping the original axioms, and because my ontology is in EL, I wanted to use ELK and have an ontology with both the original axioms and the axioms created by ELK.

**Comment by ykazakov** [comment] 2021-12-17 11:05
Can you provide your ontology? Or at least a part that is used to infer the axioms not found be ELK (use explain inference in Protege).

**Comment by MajlindaLlugiqi** [comment] 2021-12-17 11:13
This is one of the ontologies that I am using.

**Comment by ykazakov** [comment] 2021-12-17 13:28
@MajlindaLlugiqi I think you have forgotten to link/attach the ontology.

**Comment by MajlindaLlugiqi** [comment] 2021-12-17 13:39
.owl file is not supported here, thus I have attached in the email. Here it is as a zip file.
[heart_dataset_ontology.owl.zip](https://github.com/liveontologies/elk-reasoner/files/7735489/heart_dataset_ontology.owl.zip)

**Comment by ykazakov** [comment] 2021-12-17 14:09
Thanks! Please tell me the versions of OWL API, HermiT, and ELK that you are using.

**Comment by ykazakov** [comment] 2021-12-17 14:21
I tried this code adapted from yours with:

- OWL API 4.5.20
- ELK 0.4.3
- HemiT 1.3.8.413

```java
package org.liveontologies.bugs;

import java.io.File;
import java.util.Collections;
import java.util.List;

import org.semanticweb.HermiT.ReasonerFactory;
import org.semanticweb.elk.owlapi.ElkReasonerFactory;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.formats.FunctionalSyntaxDocumentFormat;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;
import org.semanticweb.owlapi.reasoner.InferenceType;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import org.semanticweb.owlapi.reasoner.OWLReasonerFactory;
import org.semanticweb.owlapi.util.InferredAxiomGenerator;
import org.semanticweb.owlapi.util.InferredOntologyGenerator;
import org.semanticweb.owlapi.util.InferredSubClassAxiomGenerator;

public class Issue62 {

	public static void main(String[] args)
			throws OWLOntologyStorageException, OWLOntologyCreationException {
		
		OWLOntologyManager inputOntologyManager = OWLManager
				.createOWLOntologyManager();
		OWLOntologyManager manager = OWLManager
				.createOWLOntologyManager();

		// Load your ontology.
		OWLOntology ont = inputOntologyManager
				.loadOntologyFromOntologyDocument(new File("/tmp/heart_dataset_ontology.owl"));
		
		
		// Create an ELK reasoner.
		OWLReasonerFactory reasonerFactory = new ElkReasonerFactory();
		// Uncomment to use a HermiT reasoner
//		reasonerFactory = new ReasonerFactory();
		OWLReasoner reasoner = reasonerFactory.createReasoner(ont);

				
	    reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY);
	    List<InferredAxiomGenerator<? extends OWLAxiom>> gens = Collections.singletonList(
	            new InferredSubClassAxiomGenerator());
	    OWLOntology infOnt = manager.createOntology();
	    InferredOntologyGenerator iog = new InferredOntologyGenerator(reasoner, gens);
	    OWLDataFactory f = OWLManager.getOWLDataFactory();
	    iog.fillOntology(manager.getOWLDataFactory(), infOnt);

//	     Save the inferred ontology.
	    manager.saveOntology(infOnt, new FunctionalSyntaxDocumentFormat(), IRI.create((new File("/tmp/heart_dataset_ontology-inferred.owl." + reasonerFactory.getReasonerName()).toURI())));
	}

}
```

In generates for me identical inferred axioms for your ontology regardless whether I use ELK or HermiT:

<details><summary>Inferred Axioms</summary>

```
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)


Ontology(
Declaration(Class(<http://www.semanticweb.org/heart_dataset#105590001>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#113257007>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#119297000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#123037004>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#123038009>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#129266000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#138875005>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#194828000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#22253000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#258140000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#260787004>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#263495000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#271062006>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#272099008>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#278844005>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#29857009>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#300995000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#3030002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#30766002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#310611001>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#362981000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#363787002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#365794002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#37782003>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#397669002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#404684003>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#412808005>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#417163006>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#428630002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#429622005>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#449735000>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#462575001>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#51185008>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#52302001>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#64572001>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#67079006>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#706643005>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#71388002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#719984002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#722243006>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#75367002>))
Declaration(Class(<http://www.semanticweb.org/heart_dataset#80891009>))
############################
#   Classes
############################

# Class: <http://www.semanticweb.org/heart_dataset#105590001> (<http://www.semanticweb.org/heart_dataset#105590001>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#105590001> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#113257007> (<http://www.semanticweb.org/heart_dataset#113257007>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#113257007> <http://www.semanticweb.org/heart_dataset#123037004>)

# Class: <http://www.semanticweb.org/heart_dataset#119297000> (<http://www.semanticweb.org/heart_dataset#119297000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#119297000> <http://www.semanticweb.org/heart_dataset#123038009>)

# Class: <http://www.semanticweb.org/heart_dataset#123037004> (<http://www.semanticweb.org/heart_dataset#123037004>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#123037004> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#123038009> (<http://www.semanticweb.org/heart_dataset#123038009>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#123038009> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#129266000> (<http://www.semanticweb.org/heart_dataset#129266000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#129266000> <http://www.semanticweb.org/heart_dataset#362981000>)

# Class: <http://www.semanticweb.org/heart_dataset#138875005> (<http://www.semanticweb.org/heart_dataset#138875005>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#138875005> owl:Thing)

# Class: <http://www.semanticweb.org/heart_dataset#194828000> (<http://www.semanticweb.org/heart_dataset#194828000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#194828000> <http://www.semanticweb.org/heart_dataset#29857009>)
SubClassOf(<http://www.semanticweb.org/heart_dataset#194828000> <http://www.semanticweb.org/heart_dataset#417163006>)

# Class: <http://www.semanticweb.org/heart_dataset#22253000> (<http://www.semanticweb.org/heart_dataset#22253000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#22253000> <http://www.semanticweb.org/heart_dataset#404684003>)

# Class: <http://www.semanticweb.org/heart_dataset#258140000> (<http://www.semanticweb.org/heart_dataset#258140000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#258140000> <http://www.semanticweb.org/heart_dataset#363787002>)

# Class: <http://www.semanticweb.org/heart_dataset#260787004> (<http://www.semanticweb.org/heart_dataset#260787004>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#260787004> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#263495000> (<http://www.semanticweb.org/heart_dataset#263495000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#263495000> <http://www.semanticweb.org/heart_dataset#278844005>)

# Class: <http://www.semanticweb.org/heart_dataset#271062006> (<http://www.semanticweb.org/heart_dataset#271062006>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#271062006> <http://www.semanticweb.org/heart_dataset#52302001>)

# Class: <http://www.semanticweb.org/heart_dataset#272099008> (<http://www.semanticweb.org/heart_dataset#272099008>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#272099008> <http://www.semanticweb.org/heart_dataset#362981000>)

# Class: <http://www.semanticweb.org/heart_dataset#278844005> (<http://www.semanticweb.org/heart_dataset#278844005>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#278844005> <http://www.semanticweb.org/heart_dataset#363787002>)

# Class: <http://www.semanticweb.org/heart_dataset#29857009> (<http://www.semanticweb.org/heart_dataset#29857009>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#29857009> <http://www.semanticweb.org/heart_dataset#22253000>)

# Class: <http://www.semanticweb.org/heart_dataset#300995000> (<http://www.semanticweb.org/heart_dataset#300995000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#300995000> <http://www.semanticweb.org/heart_dataset#194828000>)

# Class: <http://www.semanticweb.org/heart_dataset#3030002> (<http://www.semanticweb.org/heart_dataset#3030002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#3030002> <http://www.semanticweb.org/heart_dataset#363787002>)

# Class: <http://www.semanticweb.org/heart_dataset#30766002> (<http://www.semanticweb.org/heart_dataset#30766002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#30766002> <http://www.semanticweb.org/heart_dataset#362981000>)

# Class: <http://www.semanticweb.org/heart_dataset#310611001> (<http://www.semanticweb.org/heart_dataset#310611001>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#310611001> <http://www.semanticweb.org/heart_dataset#363787002>)

# Class: <http://www.semanticweb.org/heart_dataset#362981000> (<http://www.semanticweb.org/heart_dataset#362981000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#362981000> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#363787002> (<http://www.semanticweb.org/heart_dataset#363787002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#363787002> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#365794002> (<http://www.semanticweb.org/heart_dataset#365794002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#365794002> <http://www.semanticweb.org/heart_dataset#404684003>)

# Class: <http://www.semanticweb.org/heart_dataset#37782003> (<http://www.semanticweb.org/heart_dataset#37782003>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#37782003> <http://www.semanticweb.org/heart_dataset#123037004>)

# Class: <http://www.semanticweb.org/heart_dataset#397669002> (<http://www.semanticweb.org/heart_dataset#397669002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#397669002> <http://www.semanticweb.org/heart_dataset#272099008>)

# Class: <http://www.semanticweb.org/heart_dataset#404684003> (<http://www.semanticweb.org/heart_dataset#404684003>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#404684003> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#412808005> (<http://www.semanticweb.org/heart_dataset#412808005>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#412808005> <http://www.semanticweb.org/heart_dataset#71388002>)

# Class: <http://www.semanticweb.org/heart_dataset#417163006> (<http://www.semanticweb.org/heart_dataset#417163006>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#417163006> <http://www.semanticweb.org/heart_dataset#64572001>)

# Class: <http://www.semanticweb.org/heart_dataset#428630002> (<http://www.semanticweb.org/heart_dataset#428630002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#428630002> <http://www.semanticweb.org/heart_dataset#258140000>)

# Class: <http://www.semanticweb.org/heart_dataset#429622005> (<http://www.semanticweb.org/heart_dataset#429622005>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#429622005> <http://www.semanticweb.org/heart_dataset#3030002>)

# Class: <http://www.semanticweb.org/heart_dataset#449735000> (<http://www.semanticweb.org/heart_dataset#449735000>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#449735000> <http://www.semanticweb.org/heart_dataset#37782003>)

# Class: <http://www.semanticweb.org/heart_dataset#462575001> (<http://www.semanticweb.org/heart_dataset#462575001>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#462575001> <http://www.semanticweb.org/heart_dataset#706643005>)

# Class: <http://www.semanticweb.org/heart_dataset#51185008> (<http://www.semanticweb.org/heart_dataset#51185008>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#51185008> <http://www.semanticweb.org/heart_dataset#123037004>)

# Class: <http://www.semanticweb.org/heart_dataset#52302001> (<http://www.semanticweb.org/heart_dataset#52302001>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#52302001> <http://www.semanticweb.org/heart_dataset#71388002>)

# Class: <http://www.semanticweb.org/heart_dataset#64572001> (<http://www.semanticweb.org/heart_dataset#64572001>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#64572001> <http://www.semanticweb.org/heart_dataset#404684003>)

# Class: <http://www.semanticweb.org/heart_dataset#67079006> (<http://www.semanticweb.org/heart_dataset#67079006>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#67079006> <http://www.semanticweb.org/heart_dataset#105590001>)

# Class: <http://www.semanticweb.org/heart_dataset#706643005> (<http://www.semanticweb.org/heart_dataset#706643005>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#706643005> <http://www.semanticweb.org/heart_dataset#260787004>)

# Class: <http://www.semanticweb.org/heart_dataset#71388002> (<http://www.semanticweb.org/heart_dataset#71388002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#71388002> <http://www.semanticweb.org/heart_dataset#138875005>)

# Class: <http://www.semanticweb.org/heart_dataset#719984002> (<http://www.semanticweb.org/heart_dataset#719984002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#719984002> <http://www.semanticweb.org/heart_dataset#362981000>)

# Class: <http://www.semanticweb.org/heart_dataset#722243006> (<http://www.semanticweb.org/heart_dataset#722243006>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#722243006> <http://www.semanticweb.org/heart_dataset#362981000>)

# Class: <http://www.semanticweb.org/heart_dataset#75367002> (<http://www.semanticweb.org/heart_dataset#75367002>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#75367002> <http://www.semanticweb.org/heart_dataset#310611001>)

# Class: <http://www.semanticweb.org/heart_dataset#80891009> (<http://www.semanticweb.org/heart_dataset#80891009>)

SubClassOf(<http://www.semanticweb.org/heart_dataset#80891009> <http://www.semanticweb.org/heart_dataset#113257007>)
SubClassOf(<http://www.semanticweb.org/heart_dataset#80891009> <http://www.semanticweb.org/heart_dataset#51185008>)


)
```
</details>

**Comment by MajlindaLlugiqi** [comment] 2021-12-18 11:03
For HermiT I used reasoning in Protege (HermiT 1.4.3), and ELK (0.4.3)

Attached you may see that the number of axioms when using HermiT is 329 whereas when using ELK is 85. It is probably because we are using CLASS_HIERARCHY inference type, and that's why I asked is there a way to use multiple inference-types. Moreover number of object property count is 0 after reasoning with ELK.

<img width="495" alt="Screen Shot 2021-12-18 at 12 03 22" src="https://user-images.githubusercontent.com/47790826/146638704-146ab6ea-9cb2-4ca2-a1e9-f6c6fcc0e888.png">

**Comment by ykazakov** [comment] 2021-12-18 11:21
But only 54 of them are logical axioms. What are the remaining 275? From where do you see that all original axioms are included?

**Comment by ykazakov** [comment] 2024-03-27 11:32
I am closing this issue as I could not reproduce the problem. Feel free to reopen if you think that the problem still takes place.

**Closed by ykazakov** 2024-03-27 11:32 UTC
