### ISSUE TITLE
Exception in thread "http-bio-8080-Acceptor-0" java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by spolavar** [liveontologies/elk-reasoner#37] opened 2016-04-29 01:37 UTC
Hi,
I have a Java application running on the apache tomcat server which uses ELK reasoner via OWLAPI. I have this application running on two different server machines, on one it works fine, but on the other it keeps throwing this error:

Exception in thread "http-bio-8080-exec-1849" java.lang.OutOfMemoryError: PermGen space
Apr 28, 2016 2:30:10 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/neuroMorphoReview] appears to have started a thread named [elk-reasoner-thread-3] but has failed to stop it. This is very likely to create a memory leak.

sometimes I see more detail like this:

Exception in thread "http-bio-8080-Acceptor-0" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:713)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:162)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:142)
        at org.apache.tomcat.util.net.JIoEndpoint.processSocket(JIoEndpoint.java:531)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:234)
        at java.lang.Thread.run(Thread.java:744)

I am hoping that you will be able to help me fix this! 

Thank you
Sridevi

**Comment by ykazakov** [comment] 2016-04-29 06:37
Seems like duplicate of #36 
I would be grateful if you could help diagnosing it like described there. Particularly, check how many elk threads are created.

**Closed** 2016-04-29 06:38 UTC
Labels: duplicate
