### ISSUE TITLE
Version 0.5

### ISSUE THREAD

**Issue by mosfet80** [liveontologies/elk-reasoner#68] opened 2024-03-26 05:13 UTC
the latest version, 0.4.3, was released several years ago. If possible, it would be very useful to release a 0.5 version

**Comment by ykazakov** [comment] 2024-03-27 11:27
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.

**Comment by ykazakov** [comment] 2024-03-27 11:28
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.

**Comment by ykazakov** [comment] 2024-03-27 11:29
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.

**Closed by ykazakov** 2024-03-27 11:29 UTC
